### ISSUE TITLE
Error running git command in GitHub actions

### ISSUE THREAD

**Issue by wmonk** [hipstersmoothie/jest-github-reporter#123]
Just set this up and using in GitHub Actions, and this is the error returned.

```
Error: Command failed with exit code 128: git rev-parse HEAD^1
fatal: ambiguous argument 'HEAD^1': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
HEAD^1
    at makeError (/home/runner/work/redacted/redacted/node_modules/create-check/node_modules/execa/lib/error.js:59:11)
    at handlePromise (/home/runner/work/redacted/redacted/node_modules/create-check/node_modules/execa/index.js:114:26)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

Any ideas on this?

**Comment by hipstersmoothie** [comment]
Github actions does a shallow checkout. I recommend the following:

```yaml
    steps:
      - uses: actions/checkout@v2

      - name: Prepare repository
        run: git fetch --unshallow --tags
```
